libjpeg_turbo_build_rule = """
cc_library(
    name = "libjpeg_headers",
    hdrs = [
        "jconfig.h",
        "jdct.h",
        "jinclude.h",
        "jmorecfg.h",
        "jpeglib.h",
        "jpeglibmangler.h",
    ],
    visibility = ["//visibility:public"],
)


cc_library(
    name = "libjpeg",
    srcs = [
        "jcapimin.c",
        "jcapistd.c",
        "jccoefct.c",
        "jccolor.c",
        "jcdctmgr.c",
        "jchuff.c",
        "jcicc.c",
        "jcinit.c",
        "jcmainct.c",
        "jcmarker.c",
        "jcmaster.c",
        "jcomapi.c",
        "jcparam.c",
        "jcphuff.c",
        "jcprepct.c",
        "jcsample.c",
        "jctrans.c",
        "jdapimin.c",
        "jdapistd.c",
        "jdatadst.c",
        "jdatasrc.c",
        "jdcoefct.c",
        "jdcolor.c",
        "jddctmgr.c",
        "jdhuff.c",
        "jdicc.c",
        "jdinput.c",
        "jdmainct.c",
        "jdmarker.c",
        "jdmaster.c",
        "jdmerge.c",
        "jdphuff.c",
        "jdpostct.c",
        "jdsample.c",
        "jdtrans.c",
        "jerror.c",
        "jerror.h",
        "jfdctflt.c",
        "jfdctfst.c",
        "jfdctint.c",
        "jidctflt.c",
        "jidctfst.c",
        "jidctint.c",
        "jidctred.c",
        "jmemmgr.c",
        "jmemnobs.c",
        "jpeg_nbits_table.c",
        "jquant1.c",
        "jquant2.c",
        "jutils.c",
        "jsimd_none.c",
    ],
    hdrs = [
        "jpegint.h",
        "jmemsys.h",
        "jchuff.h",
        "jdhuff.h",
        "jversion.h",
        "jdcoefct.h",
        "jdmainct.h",
        "jpegcomp.h",
        "jsimd.h",
        "jdsample.h",
        "jconfigint.h",
        "jsimddct.h",
        "jdmaster.h",
        "jstdhuff.c",
        "jccolext.c",
        "jdcolext.c",
        "jpeg_nbits_table.h",
        "jdmrgext.c",
        "jdmrg565.c",
        "jdcol565.c",        
    ],
    deps = [":libjpeg_headers"],
    visibility = ["//visibility:public"],
)

"""