re2_build_rule = """
cc_library(
    name = "re2",
    srcs = [
        "re2/bitstate.cc",
        "re2/compile.cc",
        "re2/dfa.cc",
        "re2/filtered_re2.cc",
        "re2/mimics_pcre.cc",
        "re2/nfa.cc",
        "re2/onepass.cc",
        "re2/parse.cc",
        "re2/perl_groups.cc",
        "re2/prefilter.cc",
        "re2/prefilter_tree.cc",
        "re2/prog.cc",
        "re2/re2.cc",
        "re2/regexp.cc",
        "re2/set.cc",
        "re2/simplify.cc",
        "re2/stringpiece.cc",
        "re2/tostring.cc",
        "re2/unicode_casefold.cc",
        "re2/unicode_groups.cc",
        "util/pcre.cc",
        "util/rune.cc",
        "util/strutil.cc",
    ],
    hdrs = [
        "re2/bitmap256.h",
        "re2/prefilter.h",
        "re2/prog.h",
        "re2/regexp.h",
        "re2/unicode_casefold.h",
        "re2/unicode_groups.h",
        "re2/walker-inl.h",
        "re2/filtered_re2.h",
        "re2/re2.h",
        "re2/set.h",
        "re2/prefilter_tree.h",
        "re2/stringpiece.h",
        "util/flags.h",
        "util/logging.h",
        "util/mix.h",
        "util/sparse_set.h",
        "util/mutex.h",
        "util/strutil.h",
        "util/utf.h",
        "util/pcre.h",
        "util/util.h",
        "util/sparse_array.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "re2_bench_util",
    srcs = [
        "util/benchmark.cc",
    ],
    hdrs = [
        "re2/re2.h",
        "re2/stringpiece.h",
        "util/util.h",
        "util/flags.h",
        "util/benchmark.h",
    ],
    visibility = ["//visibility:public"],
)
"""