<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
  <title>Title of the document </title>
</head>
<body>
<ul>
  <li data-thumb="a.jpg">
    <?php
    header('X-My-PHP-Header: with_flush');
    flush();
    echo"Content generated by PHP with a call to flush()!";
    ?>
    <img src="a.jpg"/>
   </li>
</ul>
</body>
</html>
